### ISSUE TITLE
Importing courses from a previous IPA year does not create sectionGroups

### ISSUE THREAD

**Issue by cthielen** [ucdavis/ipa-client-angular#1444]
Fixed on 'import-from-ipa'
----
I imported my IPA 2019-2020 schedule into 2020-2021 and while the courses and tags were copied, no offerings existed.

Is this the desired behavior? I'm assuming not. Reported by Caitlyn of Blue Cluster.

**Comment by cthielen** [comment]
This implies both 'Import days and times' as well as 'Copy instructors' are broken for this scenario.

**Comment by ltwheeler** [comment]
Psychology doesn't appear to have a 2019-2020 schedule currently, so I assume she means 2018-2019 schedule into 2019-2020.

I was able to replicate the bug, sectionGroups were not created due to an error in:
https://github.com/ucdavis/ipa-web/commit/56a757bc714b4eaebbfa640bd8d36ab40a829023#diff-4abc7657db7c737ef782f5767b511b48

That erroneously deleted the historicalCourse variable back on September 22nd.

I added additional documentation and renamed the variables for clarity to hopefully avoid this happening again.
